### ISSUE TITLE
bind_user(user, passwd) returns TypeError

### ISSUE THREAD

**Issue by mkell43** [admiralobvious/flask-simpleldap#14]
Hey,

I found issue #6, but it was closed due to the original request never being following through on.  I'm getting the same thing however.

My app.config settings.

```python
    # LDAP Auth Configuration
    app.config['LDAP_HOST'] = 'myldap.server'
    app.config['LDAP_BASE_DN'] = 'dc=unitdc,dc=orgdc,dc=typedc'
    app.config['LDAP_USERNAME'] = 'cn=managercn,dc=unitdc,dc=orgdc,dc=typedc'
    app.config['LDAP_PASSWORD'] = 'mypass'
    app.config['LDAP_USE_TLS'] = True
    app.config['LDAP_USER_OBJECT_FILTER'] = '(&(objectclass=posixAccount)(cn=%s))'
```

I confirmed that the LDAP server is responding with a record and tracked it back as far as I could on my own.  What I found was that the var "who" in python-ldap's simple bind function was where the dict was being sent to.  That was being generated by the get_object_details in flask-simpleldap.

Now I'm not certain that this is an actual bug / issue with flask-simpleldap, in fact I'm willing to bet it's a configuration error on my end.  But if you could hopefully point out what I'm missing I would appreciate it.

The traceback is below.

Thanks.

```python
Traceback (most recent call last):
  File "/Users/mkeller/venvs/dopplr/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/mkeller/venvs/dopplr/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/mkeller/venvs/dopplr/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mkeller/venvs/dopplr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mkeller/venvs/dopplr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mkeller/venvs/dopplr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mkeller/venvs/dopplr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mkeller/venvs/dopplr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/mkeller/PycharmProjects/dopplr/dopplr_web/__init__.py", line 148, in login
    test = ldap.bind_user(user, passwd)
  File "/Users/mkeller/venvs/dopplr/lib/python2.7/site-packages/flask_simpleldap/__init__.py", line 147, in bind_user
    conn.simple_bind_s(user_dn, password)
  File "/Users/mkeller/venvs/dopplr/lib/python2.7/site-packages/ldap/ldapobject.py", line 232, in simple_bind_s
    msgid = self.simple_bind(who,cred,serverctrls,clientctrls)
  File "/Users/mkeller/venvs/dopplr/lib/python2.7/site-packages/ldap/ldapobject.py", line 226, in simple_bind
    return self._ldap_call(self._l.simple_bind,who,cred,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls))
  File "/Users/mkeller/venvs/dopplr/lib/python2.7/site-packages/ldap/ldapobject.py", line 106, in _ldap_call
    result = func(*args,**kwargs)
TypeError: must be string, not dict```

**Comment by admiralobvious** [comment]
Hi,

If you add a print statement in "/Users/mkeller/PycharmProjects/dopplr/dopplr_web/__init__.py" under:
`test = ldap.bind_user(user, passwd)`
like this:
`print(type(user), type(passwd))`

What does it output?

**Comment by mkell43** [comment]
Sorry for my delay.

Originally after adding the print it was showing str,unicode.  So I updated from

```python
passwd = request.form['passwd']
```

to

```python
passwd = str(request.form['passwd'])
```

Now it's returning ```(<type 'str'>, <type 'str'>)``` as you stated it should, but I'm still getting the same error.

I did a dump on the last line of the traceback in the Flask debug console, I've redacted some of the info it contained obviously.

```python
({'authorizedService': ['toopher'], 'objectClass': ['inetOrgPerson', 'posixAccount', 'hostObject', 'authorizedServiceObject'], 'loginShell': ['/bin/bash'], 'userPassword': ['{CRYPT}cryptedpassword’], 'uidNumber': [‘uidnum’], 'host': [‘host1’, ‘host2’, ‘host3’], 'gidNumber': [‘gidnum’], 'sn': ['Keller'], 'homeDirectory': ['/home/mkeller'], 'uid': ['mkeller'], 'mail': ['mkeller@somedomain’], 'givenName': ['M'], 'cn': ['mkeller']  }, ‘mypassword’, None, None)
```

You can see the dict it's complaining about there.  I tracked back it's creation from the bind_user function to get_object_details.  Which is where it looks like the filters and field specifications are applied to the ldap query.  This leads me to believe that it's a setting error on my part.  But which one, I'm not entirely certain, and after sitting down with the primary LDAP admin we weren't able to figure out which one specifically needed to be filtered for either.

Thanks.

**Comment by admiralobvious** [comment]
I am not entirely sure either. Do the examples application work with your LDAP configs? Also, which LDAP server (Active Directory, OpenLDAP etc.) is this?

**Comment by jm66** [comment]
Have the same issue with openldap and having the filter ```(&(objectclass=inetOrgPerson)(userid=%s))```. I assume the problem is that certain users have more than one userid which conflicts with the code.

**Comment by jm66** [comment]
So, I've found a workaround:
```
-                    if current_app.config['LDAP_OBJECTS_DN'] in records[0][1]:
-                        dn = records[0][1][
-                            current_app.config['LDAP_OBJECTS_DN']]
-                        return dn[0]
+                    dn = records[0][0]
+                    return dn
```
Seems like the OpenLDAP structure does not contain the DN as an attribute, i.e.:

```
records[0][1]
{'telephoneNumber': ['123-456-7890'], 'uid': ['jm'], 'objectClass': ['inetOrgPerson', 'top'], 'userPassword': ['{MD5}44444reffsdfdfd=='], 'sn': ['Lopez Lujan'], 'mail': ['jm.lopez@utoronto.ca'], 'givenName': ['Jose Manuel'], 'cn': ['Jose Manuel Lopez Lujan', 'josem']}
```

The DN itself is the first element of the tuple:
```
records[0][0]
'cn=Jose Manuel Lopez Lujan,ou=ORG,dc=GROUP,dc=COMPANY,dc=DOMAIN,dc=CA'
```

**Comment by admiralobvious** [comment]
Thank you @jm66, I understand the problem now. I'll just validate that python-ldap also returns the DN has the first element of the tuple for Active Directory (99% sure it does) tomorrow and I'll fix that issue and make a new release.

Cheers!

**Comment by jm66** [comment]
Awesome. I look forward to it.
