### ISSUE TITLE
openldap does not return distinguishedName field

### ISSUE THREAD

**Issue by cyberb** [admiralobvious/flask-simpleldap#15]
Looks like OpenLDAP does not return distinguishedName on this call:
````
records = conn.search_s(current_app.config['LDAP_BASE_DN'],
                                    ldap.SCOPE_SUBTREE, query, fields)
````

result:

````
[('cn=boris,ou=users,dc=syncloud,dc=org', 
{'objectClass': ['simpleSecurityObject', 'person'], 
'description': ['LDAP administrator'], 
'userPassword': ['{SSHA}***'], 
'cn': ['boris'], 'sn': ['boris']})]
````

Is there any workaround or is it supported at all?

**Comment by admiralobvious** [comment]
Hi,

You need to set LDAP_OBJECTS_DN to whatever field you want. distinguishedName is just the default. Full list of options here: https://flask-simpleldap.readthedocs.org/en/latest/
