### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by MaxNoe** [admiralobvious/flask-simpleldap#19]

**Comment by admiralobvious** [comment]
python-ldap doesn't support Python 3, but I did find [this fork](https://github.com/pyldap/pyldap) that seems to provide it. I'll test it, see if it works and port my code to Python 3.

**Comment by MaxNoe** [comment]
The version on pypi IS the fork.

**Comment by admiralobvious** [comment]
I added Python 3.x support in the latest version, 1.0.0.

**Comment by MaxNoe** [comment]
Awesome, thanks a lot!
