### ISSUE TITLE
Question regarding OPT_REFERRALS

### ISSUE THREAD

**Issue by twllight** [admiralobvious/flask-simpleldap#20]
hello,

I've been working on trying to get ldap authentication working in an API that I've written however i've been getting a number of  errors like this: "LDAPException: Operations error". From the research I've done through the web, i've found that in a number of cases adding "l.set_option(ldap.OPT_REFERRALS,0)" is helpful. I've attempted to add the following via my app:

app.config['LDAP_OPT_REFERRALS'] = '0' 

However this hasn't provided any joy. Is there a different way to pass ldap configuration to flask-simpleldap?

**Comment by admiralobvious** [comment]
Hello,

You can't pass arbitrary ldap options like this, but I added a way to do it just now. If you pull the latest version (1.1.0) from pip, you'll be able to do something like:

```
import ldap as l
app.config['LDAP_CUSTOM_OPTIONS'] = {l.OPT_REFERRALS: 0}
```

See full example here [examples/groups/app.py](https://github.com/admiralobvious/flask-simpleldap/blob/master/examples/groups/app.py)

**Comment by twllight** [comment]
@admiralobvious Super useful thank you so much for putting this together!

**Comment by admiralobvious** [comment]
@twllight No problem!
