### ISSUE TITLE
Wrong code order in doc and README.md ?

### ISSUE THREAD

**Issue by ysymi** [admiralobvious/flask-simpleldap#24]
I install the flask-simpleldap in my project and write a demo show in the README and doc like these:
```
app = Flask(__name__)
ldap = LDAP(app)

app.config['LDAP_BASE_DN'] = 'OU=users,dc=example,dc=org'
app.config['LDAP_USERNAME'] = 'CN=user,OU=Users,DC=example,DC=org'
app.config['LDAP_PASSWORD'] = 'password'
```
then it will raise a exception with message : 
flask_simpleldap.LDAPException: LDAP_USERNAME cannot be None!

I move the line `ldap = LDAP(app)` after configs , my app will run as normal , so Is this order wrong?
ps. The code in [basic_auth example](https://github.com/admiralobvious/flask-simpleldap/blob/master/examples/basic_auth/app.py) is add configs firstly

**Comment by fengyc** [comment]
Hi, @ysymi . 

You are right, configs should be put in front of `LDAP(app)`. You could use the factory pattern like these:

    ldap = LDAP()

    def create_app(...):
        app = Flask(...)
        ldap.init_app(app)
        return app

**Comment by admiralobvious** [comment]
@ysymi, you're right, I fixed it. Thank you!
