### ISSUE TITLE
Filtering with multiple format placeholders

### ISSUE THREAD

**Issue by DavidUnzue** [admiralobvious/flask-simpleldap#27]
I would like to do a LDAP filtering like this:
```
LDAP_USER_OBJECT_FILTER = '(&(objectclass=Person)(|(mail={0})(sAMAccountName={0})))'
```
So that a user is able to authenticate using either an email address or a username, and the LDAP-search will look for one of both matches.

But it seems that this is not possible, I get the error:
```
TypeError: not all arguments converted during string formatting
```

This might be due to the changes made following issue https://github.com/admiralobvious/flask-simpleldap/issues/4

Is there a way of achieving the desired behaviour that I'm not aware of?

**Comment by admiralobvious** [comment]
@DavidUnzue Did you ever find a solution or workaround for this issue?

**Comment by DavidUnzue** [comment]
@admiralobvious I ended up not using a flask extension like this one but the python 3 fork of pyldap (https://github.com/pyldap/pyldap).
