### ISSUE TITLE
get_user_groups with OpenLDAP returns no groups

### ISSUE THREAD

**Issue by jedstrauss** [admiralobvious/flask-simpleldap#29]
get_user_groups with an OpenLDAP server returns no groups. I've been able to workaround with this change (line 220 of flask_simpleldap/__init__.py):

`def get_user_groups(self, user):
        """Returns a ``list`` with the user's groups or ``None`` if
        unsuccessful.

        :param str user: User we want groups for.
        """

        conn = self.bind
        try:
            if current_app.config['LDAP_OPENLDAP']:
                print ldap_filter.filter_format(
                        current_app.config['LDAP_GROUP_MEMBER_FILTER'],(user,))
                fields = \
                    [str(current_app.config['LDAP_GROUP_MEMBER_FILTER_FIELD'])]
                records = conn.search_s(
                    current_app.config['LDAP_BASE_DN'], ldap.SCOPE_SUBTREE,
                    ldap_filter.filter_format(
                        current_app.config['LDAP_GROUP_MEMBER_FILTER'],
                        __#(self.get_object_details(user, dn_only=True),)),
                        (user,)), # commented previous and added this line__
                    fields)`

self.get_object_details(user, dn_only=True) produces the user's DN, but I can't figure out how to format a 
search filter that works on a DN. I get the impression that it isn't possible.

**Comment by jm66** [comment]
Hi, what's the setting of `LDAP_GROUP_MEMBER_FILTER_FIELD`? I also have an OpenLDAP server and everything works just fine:

````
    LDAP_GROUP_MEMBERS_FIELD = 'uniqueMember'
    LDAP_GROUP_OBJECT_FILTER = '(&(objectclass=groupOfUniqueNames)(cn=%s))'
    LDAP_GROUP_MEMBER_FILTER = (
        '(&(cn=*)(objectclass=groupOfUniqueNames)(uniqueMember=%s))'
    )
    LDAP_GROUP_MEMBER_FILTER_FIELD = 'cn'
    LDAP_GROUP_DN_OBJECT_FILTER = (
        '(&(objectclass=groupOfUniqueNames)(entryDN=%s))'
    )
````
And yes, you can make a filter based on `entryDN`.
