### ISSUE TITLE
user_dn as bytes instead of string

### ISSUE THREAD

**Issue by Jeroen7V** [admiralobvious/flask-simpleldap#34]
I've updated to python 3.6.2 and since then I'm encountering a error. when the function calls for bind_user the following line of code returns bytes instead of a string:
`user_dn = self.get_object_details(user=username, dn_only=True)`
In the code later on there is a check to see if he should decode it or not based on the python version:
```
if user_dn is None:
    return
try:
    conn = self.initialize
    if sys.version_info[0] > 2:
        conn.simple_bind_s(user_dn, password)
    else:
        conn.simple_bind_s(user_dn.decode('utf-8'), password)
    return True
except ldap.LDAPError:
    return
```

Could this be because of this change to python 3.6.2?

> [bpo-29755](https://bugs.python.org/issue29755): Fixed the lgettext() family of functions in the gettext module. They now always return bytes.

**Comment by admiralobvious** [comment]
Fixed in 1.2.0.
