### ISSUE TITLE
Failover support

### ISSUE THREAD

**Issue by LrsK** [admiralobvious/flask-simpleldap#35]
If I have multiple redundant IPA-servers, and want my app to be able to use them all for authentication. Is failover to other LDAP-hosts supported, or does this need to be implemented by the client?

**Comment by admiralobvious** [comment]
Hello,

It's not built-in, so you'd have to do it yourself.
That being said, I never used IPA but that is usually done at the DNS-level. Let's say you have two (or more) LDAP servers, `ldap-01`, `ldap-02`, `ldap-n` ... hosting your domain (example.com) you setup a DNS record like `ldap.example.com` that points to the other servers so your clients (like a Flask application) just have to know this one URI and don't need to worry about handling fail-overs.

[It seems freeIPA can be setup in a similar way](https://www.freeipa.org/page/Deployment_Recommendations#Multi-site_deployment_awareness).

**Comment by LrsK** [comment]
Will this approach still work if I'm using ldaps? Say the request is `ldaps://ldap.example.com` which then resolves to `ldap01.example.com`, won't the client complain that the "name" in the certificate is wrong? It expects the name to be "ldap.example.com", but the response comes from "ldap01.example.com".

**Comment by admiralobvious** [comment]
It will work over `ldaps://` but as you said, not if your certificate doesn't contain all the server hostnames and the `ldap.example.com` sub-domain. Alternatively, a wildcard `*.example.com` certificate would also work.

**Comment by LrsK** [comment]
I decided to make a wrapper class that has the methods I need from LDAP, so I can still use the same decorators.

    # auth.py
    from random import randint
    from flask_simpleldap import LDAP

    class LDAPContainer(object):
        def __init__(self, app=None):
            self.ldaps = []
            if app is not None:
                hosts = app.config['LDAP_HOSTS'].replace(" ", "").split(",")
                for host in hosts:
                    app.config['LDAP_HOST'] = host
                    self.ldaps.append(LDAP(app))

        def init_app(self, app):
            if app is not None:
                hosts = app.config['LDAP_HOSTS'].replace(" ", "").split(",")
                for host in hosts:
                    print "adding LDAP server: %s" % host
                    app.config['LDAP_HOST'] = host
                    self.ldaps.append(LDAP(app))

        def basic_auth_required(self, func):
            return self.ldaps[randint(0, len(self.ldaps))-1].basic_auth_required(func)

        def get_user_groups(self, user):
            return self.ldaps[randint(0, len(self.ldaps))-1].get_user_groups(user)

        @staticmethod
        def group_required(groups=None):
            return LDAP.group_required(groups)


    auth = LDAPContainer()


Then I import `auth` in my app setup. 

Does this look reasonable? I could have made it more complex by having some kind of retry against another host if the request fails.

**Comment by LrsK** [comment]
I ended up using this class and importing an instance of it in my flask app:

```
from random import shuffle
from flask_simpleldap import LDAP
from functools import wraps
from flask import current_app


class LDAPContainer(object):
    def __init__(self):
        self.ldap_hosts = []
        self.ldap = None

    def init_app(self, app):
        if app is not None:
            hosts = app.config['LDAP_HOSTS'].replace(" ", "").split(",")
            self.ldap = LDAP(app)
            for host in hosts:
                print "adding %s" % host
                app.config['LDAP_HOST'] = host
                self.ldap_hosts.append(host)

    def get_random_order_ldap(self):
        ldap_index_list = range(0, len(self.ldap_hosts))
        shuffle(ldap_index_list)
        return ldap_index_list

    def require_auth(self, func):
        @wraps(func)
        def wrapped(*args, **kwargs):
            for i in self.get_random_order_ldap():
                try:
                    current_app.config['LDAP_HOST'] = self.ldap_hosts[i]
                    r = self.ldap.basic_auth_required(func)
                    return r(*args, **kwargs)
                except Exception as e:
                    print "Error: %s - LDAP host: %s" % (e.message, self.ldap_hosts[i])
                else:
                    return None
        return wrapped


auth = LDAPContainer()
```

Then all I needed to to was add the `@auth.require_auth` decorator to any views I want to protect.
