### ISSUE TITLE
broken authentication since 1.1.2

### ISSUE THREAD

**Issue by ToxicRoot** [admiralobvious/flask-simpleldap#36]
in your latest commit you check current python version:

user_dn = self.get_object_details(user=username, dn_only=True)

        if user_dn is None:
            return
        try:
            conn = self.initialize
            if sys.version_info[0] > 2:
                conn.simple_bind_s(user_dn, password)
            else:
                conn.simple_bind_s(user_dn.decode('utf-8'), password)
            return True
        except ldap.LDAPError:
            return

the problem is that self.get_object_details still returns bytes of strings, if you don't setup config as openldap (I'm using Win server 2012r2 provider not openldap). The dirty hack is to still decode user_dn as utf-8, no matter the version of python:
 if sys.version_info[0] > 2:
                conn.simple_bind_s(user_dn.decode('utf-8'), password)

If I set config to openldap = true, authentication works out of the box, but on group check another error occurs:
g.ldap_groups = ldap.get_user_groups(user=session['user_id'])
  File "/usr/local/lib/python3.6/site-packages/flask_simpleldap/__init__.py", line 222, in get_user_groups
    (self.get_object_details(user, dn_only=True),)),
  File "/usr/local/lib/python3.6/site-packages/ldap/filter.py", line 59, in filter_format
    return filter_template % (tuple(map(escape_filter_chars,assertion_values)))
TypeError: not all arguments converted during string formatting

Hope this helps you debug, or, if I'm made wrong assumptions, then you can correct me. Thank you for your work!

**Comment by admiralobvious** [comment]
Fixed in 1.2.0.
