### ISSUE TITLE
LDAP require certificate error

### ISSUE THREAD

**Issue by oribaldi** [admiralobvious/flask-simpleldap#38]
Hi,

I am having trouble making my app work with LDAP. When I set `LDAP_REQUIRE_CERT'` and  `LDAP_CERT_PATH'` ... I get the following error when running the app:

```
Traceback (most recent call last):
  File "app.py", line 27, in <module>
    ldap = LDAP(app)
  File "/opt/conda/envs/flask/lib/python3.6/site-packages/flask_simpleldap/__init__.py", line 27, in __init__
    self.init_app(app)
  File "/opt/conda/envs/flask/lib/python3.6/site-packages/flask_simpleldap/__init__.py", line 73, in init_app
    current_app.config['LDAP_CERT_PATH'])
  File "/opt/conda/envs/flask/lib/python3.6/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/opt/conda/envs/flask/lib/python3.6/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/opt/conda/envs/flask/lib/python3.6/site-packages/flask/globals.py", line 51, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.
```
Do you know how I can solve the problem?

I am using Python 3.6 and flask-simpleldap 1.1.2

**Comment by admiralobvious** [comment]
Hi,

Which version of Flask are you using? Does it work if you don't pass those two options?

**Comment by oribaldi** [comment]
Hi,

I am using Flask v0.12.2. If I don't pass those options I don't get the error, but I think it was still not working. I will check again later this week without those options and let you know.

**Comment by ninjasftw** [comment]
Hi,  

Could this be reopened?  

I am seeing the same error.
Have a working setup using ldap.
When I try and switch to ldaps using:
app.config['LDAP_SCHEMA'] = 'ldaps'
app.config['LDAP_PORT'] = '636'
app.config['LDAP_USE_SSL'] = 'True'
app.config['LDAP_REQUIRE_CERT'] = 'True'
app.config['LDAP_CERT_PATH'] = 'ca.crt'

I get the error
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in some way. To solve
this, set up an application context with app.app_context().  See the
documentation for more information.

I'm using
Python 3.8
Flask 1.1.1
Flask-SimpleLDAP 1.4.0

**Comment by ceterumcenseo146** [comment]
Exactly the same for me. But using Python 3.6
