### ISSUE TITLE
Auto change LDAP_PORT to 636 if LDAP_SCHEMA is ldaps?

### ISSUE THREAD

**Issue by tankywoo** [admiralobvious/flask-simpleldap#39]
Just an advice, standard port for ldap is 389 and for ldaps is 636.

So If `LDAP_SCHEMA` is `ldaps` you can auto update `LDAP_PORT` default to 636, not only 389 no matter it is ldap or ldaps.

**Comment by admiralobvious** [comment]
Yes, I am aware but I'd rather let it configured by the user in case they run it on a different port for whatever reason, which I have seen.

**Comment by admiralobvious** [comment]
Yes, I am aware but I'd rather let it configured by the user in case they run it on a different port for whatever reason, which I have seen.

**Comment by tankywoo** [comment]
@admiralobvious yes, but IMO, most case user will ignore LDAP_PORT this configuration and think it should use the default port. As my situation, I change my ldap server to ldaps, and change the ldap host, and enable ldap schema, but not work, after catch packet I realize I am missing the LDAP_PORT ... 😢

**Comment by tankywoo** [comment]
More I think, if user use port 389 for ldaps, aha, so maybe you are right, leave only one default port, and let user configured. Maybe you can give reminder text that if user use ldaps and should remember the LDAP_PORT
