### ISSUE TITLE
AttributeError: '_AppCtxGlobals' object has no attribute 'user'

### ISSUE THREAD

**Issue by pschwede** [admiralobvious/flask-simpleldap#43]
When I try your [example](https://flask-simpleldap.readthedocs.io/en/latest/) with custom settings I get this error:

    [2017-11-29 10:54:24,331] ERROR in app: Exception on /ldap [GET]
    Traceback (most recent call last):
      File "/web/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
        response = self.full_dispatch_request()
      File "/web/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/web/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/web/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
        rv = self.dispatch_request()
      File "/web/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/web/local/lib/python2.7/site-packages/flask_simpleldap/__init__.py", line 303, in wrapped
        if g.user is None:
      File "/web/local/lib/python2.7/site-packages/werkzeug/local.py", line 347, in __getattr__
        return getattr(self._get_current_object(), name)
    AttributeError: '_AppCtxGlobals' object has no attribute 'user'

Is this error related to some wrong arguments or credentials?

**Comment by pschwede** [comment]
Is `flask-simpleldap` compatible to Flask 0.12 at all?

**Comment by matthazinski** [comment]
I couldn't get that example to work either and had to add a `before_request` hook to set the request user variable. 

The blueprints example shows how to do this: 

https://github.com/admiralobvious/flask-simpleldap/blob/master/examples/blueprints/blueprints/app.py#L32

**Comment by cyp3d** [comment]
Where exactly do you add this code? I added in the 

def register_hooks(app):
    @app.before_request
    def before_request():
        g.user = None
        if 'user_id' in session:
            # This is where you'd query your database to get the user info.
            g.user = {}
            # Create a global with the LDAP groups the user is a member of.
            g.ldap_groups = ldap.get_user_groups(user=session['user_id'])


After the app.config['LDAP*'] areas, and I am still getting the error.

**Comment by lindycoder** [comment]
I don't know if that's what you're looking for, but i was looking for HTTP based basic auth, which is achieved with basic_auth_required and not login_required

```
@app.route("/hello")
@ldap.basic_auth_required
def hello():
    return "It works!"
```

The docstring for login_required says `When applied to a view function, any unauthenticated requests will be redirected to the view named in LDAP_LOGIN_VIEW`

Maybe this should be explained in the quickstart example... or maybe this example should use basic_auth_required

Extra bits of info, if that can help someone... i had to specify
```
app.config['LDAP_HOST'] = 'my.domain.com'
app.config['LDAP_USER_OBJECT_FILTER'] = '(specialFieldName=%s)'
```
Because my ldap is not localhost and the query `(&(objectclass=Person)(userPrincipalName=%s))` doesn't seem to apply to me
