### ISSUE TITLE
Error in bind_user method

### ISSUE THREAD

**Issue by rfaoro-gpsw** [admiralobvious/flask-simpleldap#44]
I'm on Python 3.6.3 and I get this exception when I hit `line 153` in `__init__.py` (https://github.com/admiralobvious/flask-simpleldap/blob/master/flask_simpleldap/__init__.py#L153):

`AttributeError: 'str' object has no attribute 'decode'`

I changed it back to a recent commit you had in v1.1.2, which fixed the issue:
`conn.simple_bind_s(user_dn, password)` 
(instead of `conn.simple_bind_s(user_dn.decode('utf-8'), password)`)

Can we get that fix back?

**Comment by admiralobvious** [comment]
I can't just do that, because it will break for someone else. The current code actually works for me on Python 3.6.3 as well. I am trying to figure out why it doesn't work for some people. Tell me, are you using OpenLDAP as your LDAP server?

**Comment by sw-team-release-gpsw** [comment]
Running an Active Directory server.
`user_dn` is returned as a string.

**Comment by rfaoro-gpsw** [comment]
Running an Active Directory server.
`user_dn` is returned as a string.

**Comment by rfaoro-gpsw** [comment]
Can we add this?
```
if type(user_dn) == str:
    conn.simple_bind_s(user_dn, password)
else:
    conn.simple_bind_s(user_dn.decode('utf-8'), password)
```

**Comment by pschwede** [comment]
Or if you're just dealing with py3 compatibility:

```python
if sys.version_info < (3,0,):
    conn.simple_bind_s(user_dn, password)
else:
    conn.simple_bind_s(user_dn.decode('utf-8'), password)
```

@rfaoro-gpsw how about you create a fork and request @admiralobvious for a pull?

**Comment by rfaoro-gpsw** [comment]
@pschwede I can't do that because python 3 doesn't support string decoding.

What about this:
```
if sys.version_info > (3,) and type(user_dn) == str:
    conn.simple_bind_s(user_dn, password)
else:
    conn.simple_bind_s(user_dn.decode('utf-8'), password)
````
(Yes, I can create a fork and request @admiralobvious for a pr)

**Comment by logicpeters** [comment]
Also seeing this on Python 3.6.2.  Reverting to 1.1.2 fixed the issue for me.  By the way.. I am using Open LDAP and have the configuration set to True.

**Comment by lindycoder** [comment]
I confirm that this is *MAY* not a py 3 problem, it seems to be an openldap as you said @admiralobvious 

here's a simple test with a basic openldap container.

```
docker run --env LDAP_ORGANISATION="My Company" --env LDAP_DOMAIN="my-company.com" --env LDAP_ADMIN_PASSWORD="JonSn0w"  --rm -p 9003:389  osixia/openldap:1.1.11
```

Then in a python script 
```
import ldap
l = ldap.initialize("ldap://127.0.0.1:9003")
l.simple_bind_s("CN=admin,DC=my-company,DC=com", "JonSn0w")
r = l.search_s("DC=my-company,DC=com", ldap.SCOPE_SUBTREE, 'cn=admin')
print(r)
```


the result is 

```
[('cn=admin,dc=my-company,dc=com', {'objectClass': [b'simpleSecurityObject', b'organizationalRole'], 'cn': [b'admin'], 'description': [b'LDAP administrator'], 'userPassword': [b'{SSHA}eqGwmHDG99GBl/q3goOay8PmqSOpm4e/']})]
```

to make this work with openldap you need `LDAP_OPENLDAP=True` in your config, then in the code here

https://github.com/admiralobvious/flask-simpleldap/blob/master/flask_simpleldap/__init__.py#L190

you return [0][0] which is a string and not a bytes.

so to "keep it the same for everyone else" you could `.encode()` before returning when  `LDAP_OPENLDAP=True`


That being said here's a disclaimer:
- I don't think this solution is elegant
- I only tested with the openldap container
- My ldap knowledge is about 1/10

**Comment by lindycoder** [comment]
i crafted a little monkey patch, works for me:

```
def _monkey_patch_openldap_string_flask_simpleldap_1_2_0_issue_44(ldap_instance):
    import ldap

    def bind_user(self, username, password):
        user_dn = self.get_object_details(user=username, dn_only=True)

        if user_dn is None:
            return
        try:
            if type(user_dn) == bytes:
                user_dn = user_dn.decode('utf-8')

            conn = self.initialize
            conn.simple_bind_s(user_dn, password)
            return True
        except ldap.LDAPError:
            return

    import types
    ldap_instance.bind_user = types.MethodType(bind_user, ldap_instance)

    return ldap_instance

app = Flask(__name__)
# set configs on app
ldap_auth = _monkey_patch_openldap_string_flask_simpleldap_1_2_0_issue_44(LDAP(app))

# use @ldap_auth.*
```

Have a nice day :)

**Comment by lindycoder** [comment]
@ltpitt not much to explain

doc says do
```
ldap = LDAP(app)

@app.route('/ldap')
@ldap.login_required
def ldap_protected():
    return 'Success!'
```

just use my method on the first line
```
ldap = _monkey_patch_openldap_string_flask_simpleldap_1_2_0_issue_44 (LDAP(app))
```

**Comment by ltpitt** [comment]
I've also added a
`print(records)`
before
`for k, v in list(records[0][1].items()): `
in __init__.py and what I see is:
`[(None, ['ldap://ForestDnsZones.mydomain.net/DC=ForestDnsZones,DC=ipcatalogue,DC=net']), (None, ['ldap://DomainDnsZones.mydomain.net/DC=DomainDnsZones,DC=mydomain,DC=net']), (None, ['ldap://mydomain.net/CN=Configuration,DC=mydomain,DC=net'])]`

**Comment by ltpitt** [comment]
I've also added a print(records) before for k, v in list(records[0][1].items()): in __init__.py to better understand what is going on and what I see is:
[(None, ['ldap://ForestDnsZones.mydomain.net/DC=ForestDnsZones,DC=mydomain,DC=net']), (None, ['ldap://DomainDnsZones.mydomain.net/DC=DomainDnsZones,DC=mydomain,DC=net']), (None, ['ldap://mydomain.net/CN=Configuration,DC=mydomain,DC=net'])]

**Comment by lindycoder** [comment]
@ltpitt this does not look like the same problem.

The problem in this thread is string vs bytes and my monkey patch fixes this by introducing these lines:
```
            if type(user_dn) == bytes:
                user_dn = user_dn.decode('utf-8')
```
(Which must be line 33-34 in your file)

in your stack trace i see this: 
```
  File "/vagrant/flask-webapp/ldap-login-test/ldap-login-test.py", line 28, in bind_user
    user_dn = self.get_object_details(user=username, dn_only=True)
```
which happens on line 28

So it happens before my fix in my monkey patch so i guess you have another issue completely

**Comment by BlackMetalz** [comment]
Merge this commit please: https://github.com/jm66/flask-simpleldap/commit/e537f2691c375eb1db103c04e3e23d638503be80

**Comment by VicenteIranzoMaestre** [comment]
Same issue, solved applying @lindycoder code.
