### ISSUE TITLE
Splitted LDAP directory tree

### ISSUE THREAD

**Issue by sergejschelle** [admiralobvious/flask-simpleldap#45]
Hello,

I have two user groups and two organizational units (OU).
For example: User A is in the ou1 and user B is in the ou2.
All users in ou2 have a special mark in their name.
LDAP_BASE_DN for the first user is 'OU=ou1,dc=example,dc=org'
and for the second user 'OU=ou2,dc=example,dc=org'.
Is it possible to pass several LDAP_BASE_DN's?

My quick and dirty workaround is to add following code at line 181:
```
if 'special_mark' in request.authorization.username:
    records = conn.search_s('OU=ou2,dc=example,dc=org',
                                             ldap.SCOPE_SUBTREE, query, fields)
else:
    records = conn.search_s(current_app.config['LDAP_BASE_DN'],
                                             ldap.SCOPE_SUBTREE, query, fields)
```
Do you have some hint to make it better, without hard-coded changes in flask-simpleldap module?

**Comment by admiralobvious** [comment]
It's not possible to have multiple BASE_DN in python-ldap (the underlying lib) so it's not possible and won't be in flask-simpleldap as well.

You _may_ be able to use `dc=example,dc=org` as your BASE_DN and modify your search filters to search in both OU if you also set the following option:

`LDAP_CUSTOM_OPTIONS = {ldap.OPT_REFERRALS: 0}`

**Comment by sergejschelle** [comment]
Thank you for your answer. 
I'll try `LDAP_CUSTOM_OPTIONS = {ldap.OPT_REFERRALS: 0}` option and let you know if it worked for me.

**Comment by sergejschelle** [comment]
Yes, it works for me. I think it would be good if that will be documented. It will help many AD users.
