### ISSUE TITLE
group_required that acts like basic_auth_required

### ISSUE THREAD

**Issue by strachg** [admiralobvious/flask-simpleldap#49]
I'm currently looking at implementing the factory pattern example as part of an API but I need something like a "group_auth_required" that uses basic auth in the request header rather then the "group_required" function that seems to need a login page.

I'm happy to build it and supply it back to the project but if you have anything in the pipeline or this already exists but I missed it, if you could let me know, that would be appreciated.

**Comment by admiralobvious** [comment]
Is this still valid?

**Comment by strachg** [comment]
I did implementation something for my own use and haven't had a chance to check back to see if the project now covered this requirement. If you'd like me to put together a PR, I can try to find some time to put one together, else, it's all good.

**Comment by BirkirFreyr** [comment]
I know this issue has been closed, but i just stumbled on this issue looking for a solution to this exact same problem.
Is there any way to get this added to the module or to get a snippet of your implementation @strachg  ?
Unless this is already in the project and i'm just not figuring it out, in which case a link to some documentation describing the usage would be greatly appreciated

**Comment by strachg** [comment]
Hey. yeah, I didn't get around to bundling it up into a nice neat PR and then got distracted with other stuff. I'll dig it up for you. 

I just ended up monkey patching it into this module for my particular implementation. From memory I made a decorator that stores the list of groups I get back for the authenticating user in a global var in a similar way to one of the existing functions. It was for an API so it does user the login form. You have to pass the auth in the header.

**Comment by strachg** [comment]
@BirkirFreyr, Sorry for the delayed response. I forgot and then out of the blue remembered.

Like I mention, I monkey patch the updates I required and haven't gone back to try to gracefully merge them. I've made my modes available [here ](https://github.com/strachg/flask-simpleldap-mods)if you still want to see what I did.
