### ISSUE TITLE
Quickstart documentation is misleading

### ISSUE THREAD

**Issue by OptiverTimAll** [admiralobvious/flask-simpleldap#5]
I started playing with flask-simpleldap the other day, and predictably enough I started with the source-fragment from the Quickstart documentation, but I found it somewhat misleading:

* The docs call `LDAP(app)` before adding the required settings to `app.config`, which raises an exception.
* The docs use the `ldap.login_required` decorator as a standalone wrapper, but it doesn't work that way - as far as I can tell, in order to use `ldap.login_required` you need to create a login page, teach it to store the authenticated username in `g.user` and set it up in `app.config`, none of which is described in the quickstart (or even in the `ldap.login_required` docs).

I got past those and eventually found the method I was looking for (`.bind_user()`, which I was expecting would be called `.validate_user()` since the connection that gets bound to the user is discarded after validating their password), and I really like the simplicity, but I figured I should report the problems I had with the docs.

Thanks!

**Comment by pschwede** [comment]
May I re-open? I already spent hours with trial&error and calling the support of the facility where I work at to unlock my accounts to figuring this out. Luckily I'm dealing with open-source here. But this supposed to be *simple*, right?

1. @OptiverTimAll's 2nd and 3rd point are still unimproved. I'd also like to second #43 here.
2. An example for an Active Directory setup. I am not fluent in LDAPs so this would help. I guess many who quickly need a *simpleldap* module for Python could be made very happy with that.
3. The session examples (group, blueprint) lack `app.secret_key` definitions.

There might be more. I still didn't get it working.

**Comment by pschwede** [comment]
I'll likely fork to show you what I mean, soon.
