### ISSUE TITLE
get_object_details returning None

### ISSUE THREAD

**Issue by donndurk** [admiralobvious/flask-simpleldap#62]
I can't get any results from get_object_details as an if statement on line 200 always fails.
Any help would be appreciated.

Python == 3.7.3
Flask-SimpleLDAP == 1.3.0

`if type(records[0][1]) == 'dict'` returns `False`. `print(type(records[0][1]))` outputs `<class 'dict'>`

It appears as though changing the line to `if isinstance(records[0][1], dict):` fixes the problem.

**Comment by admiralobvious** [comment]
Fixed in v1.4.0.
