### ISSUE TITLE
Wrapper ldap.group_required not working as expected

### ISSUE THREAD

**Issue by meroupatate** [admiralobvious/flask-simpleldap#64]
When using the provided [example](https://github.com/admiralobvious/flask-simpleldap/blob/master/examples/groups/app_oldap.py)  for OpenLDAP, the array g.ldap_groups is an array of bytes type whereas the wrapper is checking for string values.
If I try to run the code as it is in the example (with Python 3.7), the URL with group restriction will always return a "401 Unauthorized" error.
Replacing the wrapper `@ldap.group_required(groups=['web-developers'])` with `@ldap.group_required(groups=[b'web-developers']) ` is the solution that worked fine for me, but maybe there is a better workaround.

**Comment by mryauch** [comment]
I just came back to an old project that was using this and found the exact same problem and workaround. It looks like it was broken here:
https://github.com/admiralobvious/flask-simpleldap/compare/v1.3.2...master#diff-df961969fdc0fcec2f458e0fbb16eef9

I've cloned and tested and found that adding calls to .decode() resolves it inside of get_user_groups.
